org.gradle.jvmargs=\
  -Dfile.encoding=UTF-8 \
  -XX:SoftRefLRUPolicyMSPerMB=1 \
  -XX:+HeapDumpOnOutOfMemoryError \
  -Xmx4g \
  -Xms4g

kotlin.daemon.jvmargs=\
  -Dfile.encoding=UTF-8 \
  -XX:SoftRefLRUPolicyMSPerMB=1 \
  -XX:+HeapDumpOnOutOfMemoryError \
  -Xmx4g \
  -Xms4g

org.gradle.caching=true

org.gradle.isolated-projects=true

kotlin.code.style=official
