org.gradle.jvmargs=\
  -Dfile.encoding=UTF-8 \
  -XX:SoftRefLRUPolicyMSPerMB=1 \
  -XX:+HeapDumpOnOutOfMemoryError \
  -Xmx4g \
  -Xms4g
org.gradle.caching=true
org.gradle.isolated-projects=true

kotlin.daemon.jvmargs=\
  -Dfile.encoding=UTF-8 \
  -XX:SoftRefLRUPolicyMSPerMB=1 \
  -XX:+HeapDumpOnOutOfMemoryError \
  -Xmx4g \
  -Xms4g
kotlin.code.style=official

roborazzi.test.verify=true
roborazzi.record.filePathStrategy=relativePathFromRoborazziContextOutputDirectory
