name: Small Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          distribution: ${{ vars.JAVA_DISTRIBUTION }}
          java-version: ${{ vars.JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Unit tests
        run: ./gradlew testDebugUnitTest
